### ISSUE TITLE
SDK was built without full bitcode

### ISSUE THREAD

**Issue by Yozine** [bluebillywig/playerSdkLibraries#7]
Archiving with the BlueBillywigPlayerSDK gives the following error:

`❌  ld: bitcode bundle could not be generated because '/Users/~/Pods/BlueBillywigPlayerSDK/BlueBillywigPlayerSDK.framework/BlueBillywigPlayerSDK(BBComponent.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/~/~/BlueBillywigPlayerSDK/BlueBillywigPlayerSDK.framework/BlueBillywigPlayerSDK' for architecture arm64`

Podfile contents:

```
# platform :ios, '9.0'

target 'TestProject' do
  use_frameworks!
... 
...
  pod 'BlueBillywigPlayerSDK'
end
```

BlueBillywigPlayerSDK Version: 1.4.1.32

Enable Bitcode is set to 'YES' in App target. 
Reverting to 1.4.1.21 works.

**Comment by fgroenendijk** [comment]
Hello Yozine, there is a new library pushed today that is built with full bitcode. This should solve your issue.
